### ISSUE TITLE
Apply style bug

### ISSUE THREAD

**Issue by homoparadoksuma** [eugene-ga/ai-scripts#10]
Apply style применяет только первый скрипт к первому шаблону, а остальные сохраняет в виде исходных градиентов.

Win 10, AI 2017 21.0.2 (64bit)

**Comment by homoparadoksuma** [comment]
вероятно причина в том, что на градиент была наложена клиппинг маска

**Comment by ghost** [comment]
Остался ли баг в новой версии, после исправления #13?
Если остался, добавь пожалуйста тестовые файлы, чтобы воспроизвести. Можно в почту.

**Comment by ghost** [comment]
obsolete
