### ISSUE TITLE
Apply style: clipping mask

### ISSUE THREAD

**Issue by homoparadoksuma** [eugene-ga/ai-scripts#13]
Пожелание по скрипту. Если объект, к которому нужно применить стиль, лежит под маской, то в целом процесс обработки получается гораздо быстрее, но наш скрипт не понимает clipping mask и спотыкается о такие файлы. Возможно ли выбирать для обработки то, что лежит под маской, при условии что маска в наличии? Очень сложно?

**Comment by ghost** [comment]
@homoparadoksuma Добавь пожалуйста тестовый темплейт с одним стилем и объект с маской. Можно в почту.
