### ISSUE TITLE
Apply Style makes the same images for different templates

### ISSUE THREAD

**Issue by vikoshkina** [eugene-ga/ai-scripts#14]
apply style. почему-то рассыпает символы не в соответствии с градиентом, а так, будто у меня чёрный квадрат - равномерно по всему полю.

**Comment by ghost** [comment]
@vikoshkina  Пришли пожалуйста для теста темплейт с одним стилем и один градиент чтоб воспроизвести баг. Можно в почту shvendala[]gmail.com. Спасибо.

**Comment by vikoshkina** [comment]
всё разрешилось. спасибо! проблема была в лишнем элементе в шаблоне для скрипта.
