### ISSUE TITLE
Prepare for stock. tempRect остается в файле

### ISSUE THREAD

**Issue by homoparadoksuma** [eugene-ga/ai-scripts#15]
После сохранения EPS в файле остается __tempRect.
Mac, illustrator 20.1.0 (2015)
![image](https://user-images.githubusercontent.com/6366257/45715118-b8370400-bb93-11e8-8093-79a3e1f878b2.png)

**Comment by ghost** [comment]
- Повторяется ли баг?
- Можно файлы, чтобы воспроизвести баг?
