### ISSUE TITLE
Jpeg-export error

### ISSUE THREAD

**Issue by homoparadoksuma** [eugene-ga/ai-scripts#8]
Windows10, AI 21.0.2

![img_09022018_133054_2](https://user-images.githubusercontent.com/6366257/36059631-95cdd57e-0e6e-11e8-9315-e5138052d934.png)
![img_09022018_133921_0](https://user-images.githubusercontent.com/6366257/36059632-96036eaa-0e6e-11e8-89cd-29796fe3c2bb.png)

**Comment by ghost** [comment]
Скрипты обновлены
Есть ли баг в новой версии?

**Comment by ghost** [comment]
obsolete
